### ISSUE TITLE
How to use prs team:xxx

### ISSUE THREAD

**Issue by raivil** [CareMessagePlatform/octoscout#9] opened 2018-02-19 19:58 UTC
@omarmeky I'm not able to use `prs team:<github-slug>`.
Can you show how to get team names?

PR: https://github.com/CareMessagePlatform/octoscout/pull/8

**Comment by omarmeky** [comment] 2018-02-20 11:59
@bruno-campos, was the latest change deployed?

**Comment by bruno-campos** [comment] 2018-02-20 13:31
@omarmeky yes Daniel deployed it yesterday and it was just re-deployed to be safe

**Comment by danielnc** [comment] 2018-02-20 13:39
@bruno-campos & @omarmeky whenever code is merged to master it's auto-deployed to the env so no need to worry

@raivil to get the teams: https://github.com/orgs/CareMessagePlatform/teams

If you don't have access to it, it might be a good idea to create a command to list all teams on octoscout :)

**Comment by danielnc** [comment] 2018-02-20 13:42
@omarmeky btw it's not working for me 

I tried with the engineering team

```
prs team:engineering
```

and no results... 


can you double check which github permissions are needed

**Comment by omarmeky** [comment] 2018-02-20 13:46
Oh I forgot about permissions. @danielnc, you need this one too:

![image](https://user-images.githubusercontent.com/5597513/36427227-88a2cb30-161a-11e8-8b98-6671871f5a06.png)

**Comment by raivil** [comment] 2018-02-20 13:49
that explains why I can't get any response.

```
octoscout> octoscout prs team:engineering
octoscout> [Tue Feb 20 2018 10:45:23 GMT-0300 (-03)] ERROR TypeError: Cannot read property 'organization' of null
    at Object.parseTeamPullRequests (/octoscout/scripts/lib/gh-parser.coffee:9:5)
    at /octoscout/scripts/github.coffee:35:24
    at IncomingMessage.<anonymous> (/octoscout/node_modules/scoped-http-client/src/index.js:95:22)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by danielnc** [comment] 2018-02-21 17:07
@omarmeky can we add please this info to the README file which permissions are required if we ever need to move octoscout to a new server?

I'll give this permission and we can try again

**Comment by danielnc** [comment] 2018-02-22 13:29
i gave this permission but still not working, not sure what the issue is

**Comment by omarmeky** [comment] 2018-02-22 15:06
Oh I see the issue

**Closed as completed** 2018-02-22 17:00 UTC
